# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

# Source - https://stackoverflow.com/a/73229032
# Posted by aknosis
# Retrieved 2025-11-07, License - CC BY-SA 4.0

version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
        interval: daily
    directory: /
