# TOML to be slightly mangled into dashing.json
# https://github.com/technosophos/dashing#usage

name = 'Sublime Merge'
package = 'sublime-merge'
index = 'docs/index.html'
icon32x32 = '../../resources/sublime-merge.png'
allowJS = false
ExternalURL = 'https://www.sublimemerge.com'
ignore = ['id', 'id0', 'id1', 'id2']

# Available 'type' values at
# # https://kapeli.com/docsets#supportedentrytypes

[[selectors.GLOBAL]]
# Each page's header
css = 'title'
type = 'Guide'

[[selectors.GLOBAL]]
# Page subheadings
css = 'h2'
type = 'Section'


[[selectors.faq]]
[[selectors.getting_started]]
[[selectors.diff_context]]


[[selectors.key_bindings]]
# Binding settings
css = 'section:has(#bindings) h3[id]'
type = 'Setting'

[[selectors.key_bindings]]
# "context" modifiers
css = 'dt'
type = 'Filter'


[[selectors.command_palette]]
[[selectors.custom_commands]]
[[selectors.linux_repositories]]
[[selectors.command_line]]


[[selectors.themes]]
css = 'dl.attributes > dt'
type = 'Attribute'

[[selectors.themes]]
css = 'dl.settings > dt'
type = 'Setting'

[[selectors.themes]]
css = 'dl.properties > dt'
type = 'Property'

[[selectors.themes]]
css = 'dl.elements > dt'
type = 'Element'

[[selectors.themes]]
# Element properties
# TODO: Maybe split these into attributes and proporties
css = 'dl.elements > dd > dl dt code'
type = 'Property'


[[selectors.menus]]
# Settings
css = '.primary section:has(#entries) dt'
type = 'Setting'

[[selectors.menus]]
# Variables
css = '.primary section:has(#available_menus) dl.enum > dt'
requiretext = '\$'
type = 'Variable'

[[selectors.menus]]
# Menus
css = '.primary section:has(#available_menus) dl.enum > dt'
requiretext = '.sublime-menu'
type = 'File'


[[selectors.packages]]
css = 'dl dd'
type = 'File'


[[selectors.minihtml]]
css = 'li code:first-child'
requiretext = 'var'
type = 'Variable'
