name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install Dashing
        run: go install github.com/technosophos/dashing@latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the docset
        run: |
          make
          make test
          make zip

      - name: Upload the ST docset
        uses: actions/upload-artifact@v4
        with:
          name: sublime-text.docset.tgz
          path: out/sublime-text.docset.tgz

      - name: Upload the SM docset
        uses: actions/upload-artifact@v4
        with:
          name: sublime-merge.docset.tgz
          path: out/sublime-merge.docset.tgz
