name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install Dashing
        run: go install github.com/technosophos/dashing@latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the docset
        run: |
          make
          make zip

      - name: Upload the ST docset
        uses: actions/upload-artifact@v4
        with:
          name: sublime-text.docset.tgz
          path: out/sublime-text.docset.tgz

      - name: Upload the SM docset
        uses: actions/upload-artifact@v4
        with:
          name: sublime-merge.docset.tgz
          path: out/sublime-merge.docset.tgz


  rolling-release:
    if: ${{ github.ref_name == 'master' && github.repository == 'SublimeText/sublime-text-docset' }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download the docsets
        uses: actions/download-artifact@v5

      - name: Update rolling prerelease
        uses: ncipollo/release-action@v1.15.0
        with:
          name: Rolling release draft
          draft: true
          allowUpdates: true
          tag: draft-release
          body: |-
            Extract the archive to a `sublime-text.docset` folder and install
            it with the instructions in the repo's ReadMe.
          artifacts: sublime-*.docset.tgz
